/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GiveawayRouteImport } from './routes/giveaway'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalculatorTradeRouteImport } from './routes/calculator-trade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JokiIndexRouteImport } from './routes/joki/index'
import { Route as FruitsIndexRouteImport } from './routes/fruits/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as JokiIdRouteImport } from './routes/joki/$id'
import { Route as FruitsIdRouteImport } from './routes/fruits/$id'
import { Route as AccountsIdRouteImport } from './routes/accounts/$id'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin/website'
import { Route as AuthenticatedAdminTradeRouteImport } from './routes/_authenticated/admin/trade'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin/promotions'
import { Route as AuthenticatedAdminJokiRouteImport } from './routes/_authenticated/admin/joki'
import { Route as AuthenticatedAdminGiveawaysRouteImport } from './routes/_authenticated/admin/giveaways'
import { Route as AuthenticatedAdminFruitsRouteImport } from './routes/_authenticated/admin/fruits'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin/faqs'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated/admin/community'
import { Route as AuthenticatedAdminChatsRouteImport } from './routes/_authenticated/admin/chats'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAiSettingsRouteImport } from './routes/_authenticated/admin/ai-settings'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin/accounts'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawayRoute = GiveawayRouteImport.update({
  id: '/giveaway',
  path: '/giveaway',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorTradeRoute = CalculatorTradeRouteImport.update({
  id: '/calculator-trade',
  path: '/calculator-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JokiIndexRoute = JokiIndexRouteImport.update({
  id: '/joki/',
  path: '/joki/',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsIndexRoute = FruitsIndexRouteImport.update({
  id: '/fruits/',
  path: '/fruits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const JokiIdRoute = JokiIdRouteImport.update({
  id: '/joki/$id',
  path: '/joki/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsIdRoute = FruitsIdRouteImport.update({
  id: '/fruits/$id',
  path: '/fruits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTradeRoute = AuthenticatedAdminTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJokiRoute = AuthenticatedAdminJokiRouteImport.update({
  id: '/joki',
  path: '/joki',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGiveawaysRoute =
  AuthenticatedAdminGiveawaysRouteImport.update({
    id: '/giveaways',
    path: '/giveaways',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFruitsRoute =
  AuthenticatedAdminFruitsRouteImport.update({
    id: '/fruits',
    path: '/fruits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChatsRoute = AuthenticatedAdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiSettingsRoute =
  AuthenticatedAdminAiSettingsRouteImport.update({
    id: '/ai-settings',
    path: '/ai-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator-trade': typeof CalculatorTradeRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/giveaway': typeof GiveawayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/fruits/$id': typeof FruitsIdRoute
  '/joki/$id': typeof JokiIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/fruits/': typeof FruitsIndexRoute
  '/joki/': typeof JokiIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/ai-settings': typeof AuthenticatedAdminAiSettingsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/fruits': typeof AuthenticatedAdminFruitsRoute
  '/admin/giveaways': typeof AuthenticatedAdminGiveawaysRoute
  '/admin/joki': typeof AuthenticatedAdminJokiRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/trade': typeof AuthenticatedAdminTradeRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator-trade': typeof CalculatorTradeRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/giveaway': typeof GiveawayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/fruits/$id': typeof FruitsIdRoute
  '/joki/$id': typeof JokiIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/fruits': typeof FruitsIndexRoute
  '/joki': typeof JokiIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/ai-settings': typeof AuthenticatedAdminAiSettingsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/fruits': typeof AuthenticatedAdminFruitsRoute
  '/admin/giveaways': typeof AuthenticatedAdminGiveawaysRoute
  '/admin/joki': typeof AuthenticatedAdminJokiRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/trade': typeof AuthenticatedAdminTradeRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculator-trade': typeof CalculatorTradeRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/giveaway': typeof GiveawayRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/fruits/$id': typeof FruitsIdRoute
  '/joki/$id': typeof JokiIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/fruits/': typeof FruitsIndexRoute
  '/joki/': typeof JokiIndexRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/ai-settings': typeof AuthenticatedAdminAiSettingsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chats': typeof AuthenticatedAdminChatsRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/fruits': typeof AuthenticatedAdminFruitsRoute
  '/_authenticated/admin/giveaways': typeof AuthenticatedAdminGiveawaysRoute
  '/_authenticated/admin/joki': typeof AuthenticatedAdminJokiRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/trade': typeof AuthenticatedAdminTradeRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator-trade'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/events'
    | '/faq'
    | '/giveaway'
    | '/sitemap.xml'
    | '/trade'
    | '/admin'
    | '/accounts/$id'
    | '/fruits/$id'
    | '/joki/$id'
    | '/accounts/'
    | '/fruits/'
    | '/joki/'
    | '/admin/accounts'
    | '/admin/ai-settings'
    | '/admin/announcements'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/chats'
    | '/admin/community'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/fruits'
    | '/admin/giveaways'
    | '/admin/joki'
    | '/admin/promotions'
    | '/admin/trade'
    | '/admin/website'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator-trade'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/events'
    | '/faq'
    | '/giveaway'
    | '/sitemap.xml'
    | '/trade'
    | '/accounts/$id'
    | '/fruits/$id'
    | '/joki/$id'
    | '/accounts'
    | '/fruits'
    | '/joki'
    | '/admin/accounts'
    | '/admin/ai-settings'
    | '/admin/announcements'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/chats'
    | '/admin/community'
    | '/admin/events'
    | '/admin/faqs'
    | '/admin/fruits'
    | '/admin/giveaways'
    | '/admin/joki'
    | '/admin/promotions'
    | '/admin/trade'
    | '/admin/website'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculator-trade'
    | '/cart'
    | '/chat'
    | '/checkout'
    | '/community'
    | '/events'
    | '/faq'
    | '/giveaway'
    | '/sitemap.xml'
    | '/trade'
    | '/_authenticated/admin'
    | '/accounts/$id'
    | '/fruits/$id'
    | '/joki/$id'
    | '/accounts/'
    | '/fruits/'
    | '/joki/'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/ai-settings'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chats'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/fruits'
    | '/_authenticated/admin/giveaways'
    | '/_authenticated/admin/joki'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/trade'
    | '/_authenticated/admin/website'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorTradeRoute: typeof CalculatorTradeRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GiveawayRoute: typeof GiveawayRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeRoute: typeof TradeRoute
  AccountsIdRoute: typeof AccountsIdRoute
  FruitsIdRoute: typeof FruitsIdRoute
  JokiIdRoute: typeof JokiIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  FruitsIndexRoute: typeof FruitsIndexRoute
  JokiIndexRoute: typeof JokiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaway': {
      id: '/giveaway'
      path: '/giveaway'
      fullPath: '/giveaway'
      preLoaderRoute: typeof GiveawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-trade': {
      id: '/calculator-trade'
      path: '/calculator-trade'
      fullPath: '/calculator-trade'
      preLoaderRoute: typeof CalculatorTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joki/': {
      id: '/joki/'
      path: '/joki'
      fullPath: '/joki/'
      preLoaderRoute: typeof JokiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits/': {
      id: '/fruits/'
      path: '/fruits'
      fullPath: '/fruits/'
      preLoaderRoute: typeof FruitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joki/$id': {
      id: '/joki/$id'
      path: '/joki/$id'
      fullPath: '/joki/$id'
      preLoaderRoute: typeof JokiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits/$id': {
      id: '/fruits/$id'
      path: '/fruits/$id'
      fullPath: '/fruits/$id'
      preLoaderRoute: typeof FruitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trade': {
      id: '/_authenticated/admin/trade'
      path: '/trade'
      fullPath: '/admin/trade'
      preLoaderRoute: typeof AuthenticatedAdminTradeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/joki': {
      id: '/_authenticated/admin/joki'
      path: '/joki'
      fullPath: '/admin/joki'
      preLoaderRoute: typeof AuthenticatedAdminJokiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/giveaways': {
      id: '/_authenticated/admin/giveaways'
      path: '/giveaways'
      fullPath: '/admin/giveaways'
      preLoaderRoute: typeof AuthenticatedAdminGiveawaysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fruits': {
      id: '/_authenticated/admin/fruits'
      path: '/fruits'
      fullPath: '/admin/fruits'
      preLoaderRoute: typeof AuthenticatedAdminFruitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chats': {
      id: '/_authenticated/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AuthenticatedAdminChatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai-settings': {
      id: '/_authenticated/admin/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AuthenticatedAdminAiSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminAiSettingsRoute: typeof AuthenticatedAdminAiSettingsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChatsRoute: typeof AuthenticatedAdminChatsRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFruitsRoute: typeof AuthenticatedAdminFruitsRoute
  AuthenticatedAdminGiveawaysRoute: typeof AuthenticatedAdminGiveawaysRoute
  AuthenticatedAdminJokiRoute: typeof AuthenticatedAdminJokiRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminTradeRoute: typeof AuthenticatedAdminTradeRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
    AuthenticatedAdminAiSettingsRoute: AuthenticatedAdminAiSettingsRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminChatsRoute: AuthenticatedAdminChatsRoute,
    AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
    AuthenticatedAdminFruitsRoute: AuthenticatedAdminFruitsRoute,
    AuthenticatedAdminGiveawaysRoute: AuthenticatedAdminGiveawaysRoute,
    AuthenticatedAdminJokiRoute: AuthenticatedAdminJokiRoute,
    AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
    AuthenticatedAdminTradeRoute: AuthenticatedAdminTradeRoute,
    AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorTradeRoute: CalculatorTradeRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GiveawayRoute: GiveawayRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeRoute: TradeRoute,
  AccountsIdRoute: AccountsIdRoute,
  FruitsIdRoute: FruitsIdRoute,
  JokiIdRoute: JokiIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  FruitsIndexRoute: FruitsIndexRoute,
  JokiIndexRoute: JokiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
